FROM maven:3-eclipse-temurin-25 AS maven
WORKDIR /opt/app
COPY src ./src
COPY pom.xml ./
RUN --mount=type=cache,target=/root/.m2 mvn -f /opt/app/pom.xml package -DskipTests

FROM eclipse-temurin:25-jre AS builder
WORKDIR /opt/app
COPY --from=maven /opt/app/target/simplecode-0.0.1-SNAPSHOT.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:25-jre
WORKDIR /opt/app
COPY --from=builder /opt/app/dependencies/ ./
COPY --from=builder /opt/app/spring-boot-loader/ ./
COPY --from=builder /opt/app/snapshot-dependencies/ ./
COPY --from=builder /opt/app/application/ ./

# Set OpenTelemetry agent as Java agent
ENV JAVA_TOOL_OPTIONS="-javaagent:/opt/app/opentelemetry-javaagent.jar"
ENV OTEL_SERVICE_NAME="java-application"
ENV OTEL_TRACES_EXPORTER="otlp"
ENV OTEL_METRICS_EXPORTER="otlp"
ENV OTEL_LOGS_EXPORTER="otlp"

ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar ./

ENTRYPOINT ["java","org.springframework.boot.loader.launch.JarLauncher"]
#ENTRYPOINT ["java","-javaagent:/opt/app/opentelemetry-javaagent.jar","org.springframework.boot.loader.launch.JarLauncher"]
